steps:
  # Step 1: Build Docker image from Dockerfile
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'asia-south2-docker.pkg.dev/project-5dd8f491-cc9c-4f1e-951/dataflow-docker-repo/dataflow-docker-repo-waqi:$BUILD_ID',
        '.'
      ]

  # Step 2: Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'asia-south2-docker.pkg.dev/project-5dd8f491-cc9c-4f1e-951/dataflow-docker-repo/dataflow-docker-repo-waqi:$BUILD_ID'
      ]

  # Step 3: Build Flex Template JSON in GCS
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      [
        'gcloud','dataflow','flex-template','build',
        'gs://temp_test_bucket_25032026/templates/waqi_flex.json',
        '--sdk-language','PYTHON',
        '--flex-template-base-image','PYTHON3',
        '--image-gcr-path','asia-south2-docker.pkg.dev/project-5dd8f491-cc9c-4f1e-951/dataflow-docker-repo/dataflow-docker-repo-waqi:$BUILD_ID',
        '--metadata-file','metadata.json',
        '--env','FLEX_TEMPLATE_PYTHON_PY_FILE=main.py',
        '--env','FLEX_TEMPLATE_PYTHON_REQUIREMENTS_FILE=requirements.txt'
      ]

  # Step 4: (Optional) Launch Dataflow job automatically
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      [
        'gcloud','dataflow','flex-template','run','waqi-dataflow-run',
        '--template-file-gcs-location','gs://temp_test_bucket_25032026/templates/waqi_flex.json',
        '--region','asia-south2'
      ]

images:
  - 'asia-south2-docker.pkg.dev/project-5dd8f491-cc9c-4f1e-951/dataflow-docker-repo/dataflow-docker-repo-waqi:$BUILD_ID'

options:
  logging: CLOUD_LOGGING_ONLY
